 Insert into places (name, location, rating) values ('Central Park', 'New York', 4.5);
 Insert into places (name, location, rating) values ('Eiffel Tower', 'Paris', 4.7);
 Insert into places (name, location, rating) values ('Colosseum', 'Rome',   4.6);   
 Insert into places (name, location, rating) values ('Great Wall of China', 'China', 4.8);
 Insert into places (name, location, rating) values ('Sydney Opera House', 'Sydney', 4.4);
 Insert into places (name, location, rating) values ('Taj Mahal', 'India', 4.9);
 Insert into places (name, location, rating) values ('Machu Picchu', 'Peru', 4.7);
 Insert into places (name, location, rating) values ('Christ the Redeemer', 'Brazil', 4.6);
 Insert into places (name, location, rating) values ('Mount Fuji', 'Japan', 4.5);
 Insert into places (name, location, rating) values ('Grand Canyon', 'USA', 4.8);   
 Insert into places (name, location, rating) values ('Stonehenge', 'UK', 4.3);
 Insert into places (name, location, rating) values ('Sagrada Familia', 'Spain', 4.7);
 Insert into places (name, location, rating) values ('Burj Khalifa', 'Dubai', 4.6);
 Insert into places (name, location, rating) values ('Angkor Wat', 'Cambodia', 4.8);
 Insert into places (name, location, rating) values ('Petra', 'Jordan', 4.7);
 Insert into places (name, location, rating) values ('Acropolis of Athens', 'Greece', 4.5);
 Insert into places (name, location, rating) values ('Neuschwanstein Castle', 'Germany', 4.6);
 Insert into places (name, location, rating) values ('Alhambra', 'Spain', 4.7);
 Insert into places (name, location, rating) values ('Chichen Itza', 'Mexico', 4.8);